<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Settings;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(['key' => 'settings_id', 'value' => '1'],
        ['key' => 'settings_created', 'value' => '2021-05-11 16:57:10'],
        ['key' => 'settings_updated', 'value' => '2022-06-06 21:02:24'],
        ['key' => 'settings_installation_date', 'value' => '2021-05-11 16:57:10'],
        ['key' => 'settings_version', 'value' => '1.04'],
        ['key' => 'settings_purchase_code', 'value' => NULL],
        ['key' => 'settings_company_name', 'value' => 'Shinko Crane Pte Ltd'],
        ['key' => 'settings_company_address_line_1', 'value' => 'Blk 46 Owen Road #01-275'],
        ['key' => 'settings_company_state', 'value' => 'Singapore'],
        ['key' => 'settings_company_city', 'value' => 'Singapore'],
        ['key' => 'settings_company_zipcode', 'value' => '210046'],
        ['key' => 'settings_company_country', 'value' => 'Singapore'],
        ['key' => 'settings_company_telephone', 'value' => '(65) 62913822'],
        ['key' => 'settings_company_customfield_1', 'value' => 'Website: www.shinkocrane.com     Email: sales@shinkocrane.com'],
        ['key' => 'settings_company_customfield_2', 'value' => 'GST Reg. No. 20-0403362-D     Reg. No. 200403362D     CR No: 73362040000G'],
        ['key' => 'settings_company_customfield_3', 'value' => NULL],
        ['key' => 'settings_company_customfield_4', 'value' => NULL],
        ['key' => 'settings_clients_registration', 'value' => 'enabled'],
        ['key' => 'settings_clients_shipping_address', 'value' => 'enabled'],
        ['key' => 'settings_clients_disable_email_delivery', 'value' => 'disabled'],
        ['key' => 'settings_clients_app_login', 'value' => 'enabled'],
        ['key' => 'settings_email_general_variables', 'value' => '{our_company_name}, {todays_date}, {email_signature}, {email_footer}, {dashboard_url}'],
        ['key' => 'settings_email_from_address', 'value' => 'sales@shinkocrane.com'],
        ['key' => 'settings_email_from_name', 'value' => 'Shinko Crane Pte Ltd'],
        ['key' => 'settings_email_server_type', 'value' => 'sendmail'],
        ['key' => 'settings_email_smtp_host', 'value' => ''],
        ['key' => 'settings_email_smtp_port', 'value' => ''],
        ['key' => 'settings_email_smtp_username', 'value' => ''],
        ['key' => 'settings_email_smtp_password', 'value' => ''],
        ['key' => 'settings_email_smtp_encryption', 'value' => 'tls'],
        ['key' => 'settings_estimates_default_terms_conditions', 'value' => '<p>Thank you for your business. We look forward to working with you on this project.</p>'],
        ['key' => 'settings_estimates_prefix', 'value' => 'EST-'],
        ['key' => 'settings_estimates_show_view_status', 'value' => 'yes'],
        ['key' => 'settings_features_billing', 'value' => 'enabled'],
        ['key' => 'settings_features_leads', 'value' => 'enabled'],
        ['key' => 'settings_features_knowledgebase', 'value' => 'enabled'],
        ['key' => 'settings_features_estimates', 'value' => 'enabled'],
        ['key' => 'settings_features_expenses', 'value' => 'enabled'],
        ['key' => 'settings_features_notes', 'value' => 'enabled'],
        ['key' => 'settings_features_subscriptions', 'value' => 'enabled'],
        ['key' => 'settings_features_contracts', 'value' => 'enabled'],
        ['key' => 'settings_features_proposals', 'value' => 'enabled'],
        ['key' => 'settings_features_tickets', 'value' => 'enabled'],
        ['key' => 'settings_files_max_size_mb', 'value' => '5000'],
        ['key' => 'settings_knowledgebase_article_ordering', 'value' => 'name-asc'],
        ['key' => 'settings_knowledgebase_allow_guest_viewing', 'value' => 'no'],
        ['key' => 'settings_knowledgebase_external_pre_body', 'value' => NULL],
        ['key' => 'settings_knowledgebase_external_post_body', 'value' => NULL],
        ['key' => 'settings_knowledgebase_external_header', 'value' => NULL],
        ['key' => 'settings_system_timezone', 'value' => 'Asia/Singapore'],
        ['key' => 'settings_system_date_format', 'value' => 'm-d-Y'],
        ['key' => 'settings_system_datepicker_format', 'value' => 'mm-dd-yyyy'],
        ['key' => 'settings_system_default_leftmenu', 'value' => 'collapsed'],
        ['key' => 'settings_system_default_statspanel', 'value' => 'collapsed'],
        ['key' => 'settings_system_pagination_limits', 'value' => '20'],
        ['key' => 'settings_system_kanban_pagination_limits', 'value' => '10'],
        ['key' => 'settings_system_currency_code', 'value' => 'SGD'],
        ['key' => 'settings_system_currency_symbol', 'value' => 's$'],
        ['key' => 'settings_system_currency_position', 'value' => 'left'],
        ['key' => 'settings_system_decimal_separator', 'value' => 'fullstop'],
        ['key' => 'settings_system_thousand_separator', 'value' => 'comma'],
        ['key' => 'settings_system_close_modals_body_click', 'value' => 'no'],
        ['key' => 'settings_system_language_default', 'value' => 'english'],
        ['key' => 'settings_system_language_allow_users_to_change', 'value' => 'yes'],
        ['key' => 'settings_system_logo_large_name', 'value' => 'logo.png'],
        ['key' => 'settings_system_logo_small_name', 'value' => 'logo-small.png'],
        ['key' => 'settings_system_logo_versioning', 'value' => '1654520544'],
        ['key' => 'settings_system_session_login_popup', 'value' => 'enabled'],
        ['key' => 'settings_system_javascript_versioning', 'value' => '2021-05-11'],
        ['key' => 'settings_tags_allow_users_create', 'value' => 'yes'],
        ['key' => 'settings_leads_allow_private', 'value' => 'yes'],
        ['key' => 'settings_leads_allow_new_sources', 'value' => 'yes'],
        ['key' => 'settings_leads_kanban_value', 'value' => 'show'],
        ['key' => 'settings_leads_kanban_date_created', 'value' => 'show'],
        ['key' => 'settings_leads_kanban_category', 'value' => 'hide'],
        ['key' => 'settings_leads_kanban_date_contacted', 'value' => 'show'],
        ['key' => 'settings_leads_kanban_telephone', 'value' => 'show'],
        ['key' => 'settings_leads_kanban_source', 'value' => 'hide'],
        ['key' => 'settings_leads_kanban_email', 'value' => 'show'],
        ['key' => 'settings_tasks_client_visibility', 'value' => 'visible'],
        ['key' => 'settings_tasks_billable', 'value' => 'billable'],
        ['key' => 'settings_tasks_kanban_date_created', 'value' => 'show'],
        ['key' => 'settings_tasks_kanban_date_due', 'value' => 'show'],
        ['key' => 'settings_tasks_kanban_date_start', 'value' => 'hide'],
        ['key' => 'settings_tasks_kanban_priority', 'value' => 'show'],
        ['key' => 'settings_tasks_kanban_client_visibility', 'value' => 'hide'],
        ['key' => 'settings_invoices_prefix', 'value' => 'INV-'],
        ['key' => 'settings_invoices_recurring_grace_period', 'value' => '3'],
        ['key' => 'settings_invoices_default_terms_conditions', 'value' => '<p>Thank you for your business.</p>'],
        ['key' => 'settings_invoices_show_view_status', 'value' => 'no'],
        ['key' => 'settings_projects_default_hourly_rate', 'value' => NULL],
        ['key' => 'settings_projects_allow_setting_permission_on_project_creation', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_files_view', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_files_upload', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_comments_view', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_comments_post', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_tasks_view', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_tasks_collaborate', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_tasks_create', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_timesheets_view', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_expenses_view', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_milestones_view', 'value' => 'yes'],
        ['key' => 'settings_projects_clientperm_assigned_view', 'value' => 'no'],
        ['key' => 'settings_projects_assignedperm_milestone_manage', 'value' => 'yes'],
        ['key' => 'settings_projects_assignedperm_tasks_collaborate', 'value' => 'yes'],
        ['key' => 'settings_stripe_secret_key', 'value' => ''],
        ['key' => 'settings_stripe_public_key', 'value' => ''],
        ['key' => 'settings_stripe_webhooks_key', 'value' => ''],
        ['key' => 'settings_stripe_default_subscription_plan_id', 'value' => NULL],
        ['key' => 'settings_stripe_currency', 'value' => 'USD'],
        ['key' => 'settings_stripe_display_name', 'value' => 'Credit Card'],
        ['key' => 'settings_stripe_status', 'value' => 'disabled'],
        ['key' => 'settings_subscriptions_prefix', 'value' => 'SUB-'],
        ['key' => 'settings_paypal_email', 'value' => 'info@example.com'],
        ['key' => 'settings_paypal_currency', 'value' => 'USD'],
        ['key' => 'settings_paypal_display_name', 'value' => 'Paypal'],
        ['key' => 'settings_paypal_mode', 'value' => 'sandbox'],
        ['key' => 'settings_paypal_status', 'value' => 'disabled'],
        ['key' => 'settings_mollie_live_api_key', 'value' => ''],
        ['key' => 'settings_mollie_test_api_key', 'value' => ''],
        ['key' => 'settings_mollie_display_name', 'value' => 'Mollie'],
        ['key' => 'settings_mollie_mode', 'value' => 'sandbox'],
        ['key' => 'settings_mollie_currency', 'value' => 'USD'],
        ['key' => 'settings_mollie_status', 'value' => 'disabled'],
        ['key' => 'settings_bank_details', 'value' => '<p><strong>This is just an example:</strong></p> <p><strong>Bank Name:</strong>&nbsp;ABCD</p> <p><strong>Account Name:</strong>&nbsp;ABCD</p> <p><strong>Account Number:</strong>&nbsp;ABCD</p>'],
        ['key' => 'settings_bank_display_name', 'value' => 'Bank Transfer'],
        ['key' => 'settings_bank_status', 'value' => 'enabled'],
        ['key' => 'settings_razorpay_keyid', 'value' => ''],
        ['key' => 'settings_razorpay_secretkey', 'value' => ''],
        ['key' => 'settings_razorpay_currency', 'value' => 'USD'],
        ['key' => 'settings_razorpay_display_name', 'value' => 'RazorPay'],
        ['key' => 'settings_razorpay_status', 'value' => 'disabled'],
        ['key' => 'settings_completed_check_email', 'value' => 'yes'],
        ['key' => 'settings_expenses_billable_by_default', 'value' => 'yes'],
        ['key' => 'settings_tickets_edit_subject', 'value' => 'yes'],
        ['key' => 'settings_tickets_edit_body', 'value' => 'yes'],
        ['key' => 'settings_theme_name', 'value' => 'default'],
        ['key' => 'settings_theme_head', 'value' => NULL],
        ['key' => 'settings_theme_body', 'value' => NULL],
        ['key' => 'settings_cronjob_has_run', 'value' => 'yes'],
        ['key' => 'settings_cronjob_last_run', 'value' => '2022-06-01 20:52:15']);

        $country = Settings::insert($data);
   }

}